global:
  scrape_interval: 10s # Standar interval scraping metrics
  evaluation_interval: 10s

scrape_configs:
  # 1. Monitoring Diri Sendiri (Prometheus)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Monitoring Microservices (Spring Boot Actuator)
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s # Lebih cepat untuk aplikasi agar grafik lebih real-time
    static_configs:
      # host.docker.internal mengarah ke localhost komputer Anda dari dalam container
      # Tambahkan port sesuai jumlah service yang Anda miliki
      - targets: ['host.docker.internal:8080', 'host.docker.internal:8081', 'host.docker.internal:8082']
        labels:
          application: 'microservices-backend'